name: Run Cross-Validation
on:
  schedule:
      - cron: '17 2 * * 1' # every monday at 02:17 UTC
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
    inputs:
      versions:
        description: 'LCG Versions, separated by comma'
        required: true
        default: '108,109,110'
        type: string
      run_dev3:
        description: 'Run latest LCG nightly build'
        type: boolean
        default: false
      jsroot_version:
        description: 'JSROOT Version (leave empty to not run tests)'
        required: false
        default: '7.11.1'
        type: string

jobs:
  cross-validation:
    if: github.repository_owner == 'root-project' || github.event_name == 'pull_request'
    name: Cross Validation
    runs-on:
      labels: [self-hosted]
    
    env:
      # run LCG releases 108, 109 and 110 for each schedules, and 110 for each PR/push
      VERSIONS: ${{ inputs.versions || (github.event_name == 'schedule' && '108,109,110' || '110') }}
      RUN_DEV3: ${{ inputs.run_dev3 == true || github.event_name == 'schedule' }}
      JSROOT_SETUP: /cvmfs/sft.cern.ch/lcg/views/LCG_110/x86_64-el9-gcc13-opt/setup.sh
      JSROOT_VERSION: ${{ inputs.jsroot_version || '~7.11.0' }} # use JSROOT version 7.11.x with newest patch version

    container:
      image: gitlab-registry.cern.ch/sft/docker/alma9-core:latest
      options: --security-opt label=disable --rm
      volumes:
        - /cvmfs/sft.cern.ch:/cvmfs/sft.cern.ch:ro
        - /cvmfs/sft-nightlies.cern.ch:/cvmfs/sft-nightlies.cern.ch:ro

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Download assets
        run: make download
      
      # add curly brackets if more than one version is given
      - name: Run Validation Suite
        run: |
          VERSIONS=$(echo "$VERSIONS" | sed 's/[^,]\+/LCG_&/g')

          if [[ "$RUN_DEV3" == "true" ]]; then
            VERSIONS="${VERSIONS},dev3/latest"
          fi

          if [[ "$VERSIONS" == *,* ]]; then
            PATTERN="{$VERSIONS}"
          else
            PATTERN="$VERSIONS"
          fi
          eval "SCRIPTS=(/cvmfs/sft.cern.ch/lcg/views/$PATTERN/x86_64-el9-gcc13-opt/setup.sh)"
          make -j$(nproc) validate source_scripts="${SCRIPTS[*]}"
        shell: bash

      - name: Run JSROOT tests
        if: ${{ env.JSROOT_VERSION != '' }}
        run: |
          source "$JSROOT_SETUP"
          npm install "jsroot@$JSROOT_VERSION"
          make -j$(nproc) validate_jsroot

      - name: Create HTML
        run: make export_html

      - name: Upload RNTuple ROOT files
        uses: actions/upload-artifact@v7
        with:
          name: RNTuple-ROOT
          path: "write/**/*.root"
          if-no-files-found: error
      - name: Upload validation JSON files
        uses: actions/upload-artifact@v7
        with:
          name: Validation-JSON
          path: "read/**/*.json"
          if-no-files-found: error

      - name: Upload HTML
        uses: actions/upload-artifact@v7
        with:
          name: validation-report
          path: ${{ github.workspace }}/web/html/cross_validation_results.html
          archive: false
          retention-days: 30
